# Generated by Django 2.2.9 on 2020-04-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0111_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
