# Generated by Django 2.2.9 on 2020-04-03 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='is_ordered',
        ),
    ]
