# Generated by Django 2.2.9 on 2020-04-04 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_auto_20200403_0112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
