# Generated by Django 2.2.9 on 2020-04-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0022_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
