# Generated by Django 2.2.9 on 2020-04-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0112_delete_wishlist'),
        ('checkout', '0025_savedlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedlist',
            name='saved_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savelines', to='product.Product'),
        ),
    ]
