# Generated by Django 2.2.9 on 2020-04-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0026_savedlist_saved_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedlist',
            name='saved_item',
        ),
    ]
