# Generated by Django 2.2.9 on 2020-04-05 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0027_remove_savedlist_saved_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Savedlist',
        ),
        migrations.AlterUniqueTogether(
            name='wishlistline',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlistline',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='wishlistline',
            name='wishlist',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.DeleteModel(
            name='WishlistLine',
        ),
    ]
